// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUczjwh-sG0HmtzzvRNKuXE2P-faPVZpE',
    appId: '1:996192439971:web:b7b03dc1dc3946a7d1f916',
    messagingSenderId: '996192439971',
    projectId: 'travelbuddy-88a72',
    authDomain: 'travelbuddy-88a72.firebaseapp.com',
    storageBucket: 'travelbuddy-88a72.firebasestorage.app',
    measurementId: 'G-4XKNTV998Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7-MPSU2tW10AIcq1i_TbNMzA3A6xGkOE',
    appId: '1:996192439971:android:4f80f11aedfa4c54d1f916',
    messagingSenderId: '996192439971',
    projectId: 'travelbuddy-88a72',
    storageBucket: 'travelbuddy-88a72.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWRVx-KuMolNoMOoL8xkl6rP9C4eJvNKg',
    appId: '1:996192439971:ios:4f0853a82f91d0abd1f916',
    messagingSenderId: '996192439971',
    projectId: 'travelbuddy-88a72',
    storageBucket: 'travelbuddy-88a72.firebasestorage.app',
    iosBundleId: 'com.example.travelBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWRVx-KuMolNoMOoL8xkl6rP9C4eJvNKg',
    appId: '1:996192439971:ios:4f0853a82f91d0abd1f916',
    messagingSenderId: '996192439971',
    projectId: 'travelbuddy-88a72',
    storageBucket: 'travelbuddy-88a72.firebasestorage.app',
    iosBundleId: 'com.example.travelBuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUczjwh-sG0HmtzzvRNKuXE2P-faPVZpE',
    appId: '1:996192439971:web:832f24124c2ac75cd1f916',
    messagingSenderId: '996192439971',
    projectId: 'travelbuddy-88a72',
    authDomain: 'travelbuddy-88a72.firebaseapp.com',
    storageBucket: 'travelbuddy-88a72.firebasestorage.app',
    measurementId: 'G-95BBSP0T6R',
  );
}
